version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "ocop"
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - app

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app


networks:
  app:
