version: '3.3'

services:
  ocop_mart_be:
    image: 
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: 
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
      DB_DROP_SCHEMA: 1
      CLOUDINARY_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
      JWT_SECRET: 
      GMAIL_USERNAME: 
      GMAIL_PASSWORD: 
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_CALLBACK_URL: 
      ZALOPAY_APP_ID: 
      ZALOPAY_KEY1: 
      ZALOPAY_KEY2: 
      ZALOPAY_RETURN_URL:
      ZALOPAY_NGROK_URL: 
      ZALOPAY_API_URL: 